### ISSUE TITLE
Bed file cannot be found

### ISSUE THREAD

**Issue by schumacherlab** [papaemmelab/toil_mutect#8]
* toil_mutect version: 1.2.2
* Python version: Python 2.7.12
* Operating System: Ubuntu Linux 16.04.5 LTS (Xenial Xerus)

### Description

I'm trying to run toil using the singularity image. Toil reports the bed file doesn't exists, but it does. Thanks for developing toil and any tips you might have!

### What I Did

```
~ cat toil.sh
singularity run /DATA/resources/singularity_containers/toil_mutect.simg toil_mutect \
  --disableChaining \
  --statePollingWait 60 \
  --maxLocalJobs 32 \
  --disableCaching \
  --realTimeLogging \
  --batchSystem CustomLSF \
  --writeLogs logs/logs_toil \
  --logFile logs/head_job.toil \
  --logLevel "INFO" \
  --normal bam/final/S7.bam \
  --tumor bam/final/S1.bam \
  --outdir toil_output \
  --bed /DATA/resources/exome_bed/twist_exome_target/Twist_Exome_Target_GRCh38.bed \
  --reference /DATA/resources/ensembl_88/fasta_dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
  --dbsnp /DATA/resources/dbsnp_grch38/All_20161122.vcf.gz \
  --kgenomes /DATA/resources/1000genomes/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz \
  --fingerprinting None

~ ./toil.sh
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
Traceback (most recent call last):
  File "/usr/local/bin/toil_mutect", line 9, in <module>
    load_entry_point('toil-mutect==1.2.2', 'console_scripts', 'toil_mutect')()
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/cli.py", line 23, in main
    commands.main()
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/commands.py", line 668, in main
    run_toil(options=options)
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/commands.py", line 498, in run_toil
    index_bam = IndexBam(options=options, runtime=short_run)
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/commands.py", line 113, in __init__
    if get_bed_size(options.bed) >= 500000:
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/utils.py", line 118, in get_bed_size
    f = open(bed_file, "r")
IOError: [Errno 2] No such file or directory: '/DATA/resources/exome_bed/twist_exome_target/Twist_Exome_Target_GRCh38.bed'

~ lt /DATA/resources/exome_bed/twist_exome_target/Twist_Exome_Target_GRCh38.bed                        -rw-rw-r-- 1 m.slagter m.slagter 43M Jan 26 17:49 /DATA/resources/exome_bed/twist_exome_target/Twist_Exome_Target_GRCh38.bed
```

**Comment by schumacherlab** [comment]
I found that the /DATA partition I'm trying to read from is not mounted from within the container.
Binding it while starting the container alleviates this problem but another one appears...

```
~ cat toil.sh
sudo /DATA/resources/singularity/bin/singularity run -B /DATA /DATA/resources/singularity_containers/toil_mutect.simg toil_mutect \
  --restart \
  --disableChaining \
  --statePollingWait 60 \
  --maxLocalJobs 32 \
  --disableCaching \
  --realTimeLogging \
  --batchSystem CustomLSF \
  --writeLogs logs/logs_toil \
  --logFile logs/head_job.toil \
  --logLevel "INFO" \
  --normal bam/final/S7.bam \
  --tumor bam/final/S1.bam \
  --outdir toil_output \
  --bed /DATA/resources/exome_bed/twist_exome_target/Twist_Exome_Target_GRCh38.bed \
  --reference /DATA/resources/ensembl_88/fasta_dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
  --dbsnp /DATA/resources/dbsnp_grch38/All_20161122.vcf.gz \
  --kgenomes /DATA/resources/1000genomes/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz \
  --fingerprinting None

~ ./toil.sh
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
DEBUG:toil.resource:Module dir is /usr/local/lib/python2.7/dist-packages
WARNING:toil.common:Requested restart but the workflow has already been completed; allowing exports to rerun.
Traceback (most recent call last):
  File "/usr/local/bin/toil_mutect", line 9, in <module>
    load_entry_point('toil-mutect==1.2.2', 'console_scripts', 'toil_mutect')()
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/cli.py", line 23, in main
    commands.main()
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/commands.py", line 668, in main
    run_toil(options=options)
  File "/usr/local/lib/python2.7/dist-packages/toil_mutect/commands.py", line 525, in run_toil
    ContainerJob.Runner.startToil(head, options)
  File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 788, in startToil
    return toil.restart()
  File "/usr/local/lib/python2.7/dist-packages/toil/common.py", line 806, in restart
    return self._jobStore.getRootJobReturnValue()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/abstractJobStore.py", line 217, in getRootJobReturnValue
    with self.readSharedFileStream('rootJobReturnValue') as fH:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/toil/jobStores/fileJobStore.py", line 447, in readSharedFileStream
    raise NoSuchFileException(sharedFileName,sharedFileName)
toil.jobStores.abstractJobStore.NoSuchFileException: File 'rootJobReturnValue' (rootJobReturnValue) does not exist.
```

**Comment by mflevine** [comment]
Hi,
A couple things.

Are you using an LSF cluster? You have the batchSystem set to CustomLSF. If so, we find that its better to pass the container to toil_mutect so that it runs the jobs in containers but the scheduler is out of the container to easily interact with the LSF system. 
```bash
 # run with singularity
 toil_mutect [TOIL-OPTIONS] [PIPELINE-OPTIONS]
     --singularity <singularity image>
     --volumes <local path> <container path>
```

As for your second issue, you are getting this error:
`WARNING:toil.common:Requested restart but the workflow has already been completed; allowing exports to rerun.`
You passed `--restart` but toil thought that the pipeline was already finished. I recommend deleting the outdir and the jobstore and trying again without restart

Hope this helps! Let us know if there is anything else we can help with.
